chonkie-ai/chonkie

- DOCS.md
- README.md
This pull request includes several updates to the documentation in `DOCS.md` and `README.md` files to improve readability and consistency. The changes primarily focus on capitalization and formatting adjustments.
* Updated section titles and table of contents entries to use consistent capitalization in `DOCS.md`. [[1]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L1-R14) [[2]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L24-R45) [[3]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L69-R71) [[4]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L95-R97) [[5]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054R108-R124) …
> Update README.md + fix DOCS.md typo

- DOCS.md
- README.md
- pyproject.toml
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
- tests/chunker/test_sentence_chunker.py
This pull request includes several updates to the `DOCS.md` documentation, as well as significant changes to the `SemanticChunker` and `SDPMChunker` classes to simplify and improve their functionality. Additionally, there are updates to the `pyproject.toml` file to reflect the current development status and dependencies.
* Improved the tone and clarity of the `DOCS.md` file, including capitalization and formatting corrections. [[1]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L3-R3) [[2]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L46-R67)
* Added a new FAQ section to the documentation.
* Removed `sentence_mode` and `spacy_model` parameters from the `SemanticChunker` and `SDPMChunker` classes, focusing on a more …
> Remove Spacy dependency from 'sentence' install + Add FAQ to DOCS.md

- pyproject.toml
This pull request updates the dependencies in the `pyproject.toml` file to ensure compatibility with newer versions and improve code maintainability. The most important changes include upgrading the `sentence-transformers` version and reformatting the `dev` dependencies for better readability.
Dependency updates:
* Updated `sentence-transformers` from version `2.0.0` to `2.3.0` in both `semantic` and `all` optional dependencies.
Code formatting:
* Reformatted the `dev` dependencies list to have each dependency on a new line for better readability.
> Update dependency version of SentenceTransformer to at least 2.3.0

- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/token.py
- src/chonkie/chunker/word.py
Several chonkers were returning incorrect indexes, either relating to the tokens or otherwise wrong. This was due to how the tokens were kept track of.
I'm not sure if the others I didn't modify are 100% correct, but they at least pass my simple tests
> [BUG] Fix the start_index and end_index to point to character indices, not token indices

- DOCS.md
Import tokenizer from "Tokenizer" not "tokenizer"
> [DOCS] Fix typo for import tokenizer in quick start example

- pyproject.toml
- src/chonkie/__init__.py
This pull request includes a version update for the `chonkie` project. The version has been incremented from `0.2.0` to `0.2.0.post1`.
Version update:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the project version to `0.2.0.post1`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L6-R6): Updated the `__version__` attribute to `0.2.0.post1`.
> Bump version to 0.2.0.post1 in pyproject.toml and __init__.py

- pyproject.toml
- src/chonkie/embeddings/__init__.py
- src/chonkie/embeddings/openai.py
- src/chonkie/embeddings/registry.py
- tests/chunker/test_semantic_chunker.py
- tests/embeddings/test_openai_embeddings.py
This pull request introduces support for OpenAI embeddings within the `chonkie` project by adding a new `OpenAIEmbeddings` class and integrating it with the existing embeddings infrastructure. The most important changes include updating dependencies, adding the new embeddings class, registering it, and creating tests for the new functionality.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R41): Added `openai` to the optional dependencies to support OpenAI embeddings.
* [`src/chonkie/embeddings/__init__.py`](diffhunk://#diff-69b9908d38d6daa74572c7f51e92812b512ae8a4ed3bdce990a436eee53c6137R3-R11): Imported `OpenAIEmbeddings` and included it in the `__all__` list to make it available for use.
* …
> Add initial OpenAIEmbeddings support to Chonkie ✨

- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
This pull request includes changes to the `semantic.py` and `sentence.py` files in the `src/chonkie/chunker` directory. The changes primarily introduce a new `min_chunk_size` parameter and modify the sentence splitting logic to use this parameter.
* [`src/chonkie/chunker/semantic.py`](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L64-R65): Added `min_chunk_size` parameter to the `__init__` method and included a validation check to ensure it is at least 1. Updated the `_split_sentences` method to use `self.min_chunk_size * 5` instead of a fixed `min_length` value. [[1]](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L64-R65) [[2]](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L99-R108) …
> [Refactor] Add min_chunk_size parameter to SemanticChunker and SentenceChunker

- pyproject.toml
- src/chonkie/__init__.py
This pull request includes updates to the version and Python requirements for the `chonkie` project. The most important changes include updating the project version and the minimum required Python version.
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R10): Updated the project version from `0.2.1` to `0.2.1.post1`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L8-R8): Updated the `__version__` attribute to `0.2.1.post1`.
Python requirements:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R10): Changed the `requires-python` field from `>=3.8` to `>=3.9`.
> [Update] Bump version to 0.2.1.post1 and require Python 3.9 or higher

- DOCS.md
This pull request includes changes to the `DOCS.md` file to update the default embedding model used in the examples for `SemanticChunker` and `SDPMChunker`.
Updates to embedding models:
* [`DOCS.md`](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L446-R446): Changed the embedding model in the `SemanticChunker` example from `"all-minilm-l6-v2"` to `"minishlab/potion-base-8M"` to reflect the default model supported with `SemanticChunker`.
* [`DOCS.md`](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L497-R497): Updated the embedding model in the `SDPMChunker` example from `"all-minilm-l6-v2"` to `"minishlab/potion-base-8M"`.
> [Update] Change default embedding model in SemanticChunkers 

- src/chonkie/chunker/base.py
This pull request includes several changes to the `src/chonkie/chunker/base.py` file to improve the handling of different tokenizer backends and provide more informative error messages. The most important changes include adding the `inspect` module to check if an object is a function, updating the initialization logic to handle different types of tokenizers, and enhancing the error messages to include the unsupported tokenizer backend type.
Improvements to tokenizer handling:
* Added import of `inspect` module to check if an object is a function. (`src/chonkie/chunker/base.py`)
* Updated the `__init__` method to first check if the `tokenizer_or_token_counter` is a string, then check if it is a function using `inspect.isfunction`, and finally assume it is a tokenizer object if neither …
> [Fix] Allow for functions as token_counters in BaseChunkers

- src/chonkie/chunker/sentence.py
This pull request includes several changes to the `src/chonkie/chunker/sentence.py` file to enhance the sentence chunking functionality. The most important changes include adding new imports, introducing a new configuration parameter, adding methods for estimating token counts, and refactoring the chunking logic to improve performance and accuracy.
Enhancements to sentence chunking:
* [`src/chonkie/chunker/sentence.py`](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cR6-R7): Added imports for `bisect_left` and `accumulate` to support new chunking logic.
* [`src/chonkie/chunker/sentence.py`](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cR86): Introduced the `use_approximate` parameter in the `__init__` method to allow for …
> Add TEVL to speed up sentence chunker

- README.md
- pyproject.toml
This pull request includes updates to the documentation links in the `README.md` file and adds a new documentation URL to the `pyproject.toml` file. The primary focus is to update the references to the new documentation site.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L9-R9): Updated various links from `DOCS.md` to `https://docs.chonkie.ai` to reflect the new documentation site. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L9-R9) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L20-R20) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L49-R49) …
> Update the docs path to docs.chonkie.ai

- src/chonkie/chunker/base.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/token.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
This pull request includes significant changes to the `SDPMChunker` and `SemanticChunker` classes to improve the chunking logic and introduce new parameters for better control over the chunking process. Key updates include the addition of new methods, parameters, and refactoring of existing logic to enhance functionality and readability.
* Added new parameters to the `SDPMChunker` class, including `mode`, `threshold`, `similarity_window`, `min_sentences`, `min_characters_per_sentence`, and `threshold_step`, to provide more control over the chunking process. (`src/chonkie/chunker/sdpm.py`)
* Introduced a new method for calculating the similarity threshold via binary search, improving the accuracy of chunking based on semantic similarity. (`src/chonkie/chunker/sdpm.py`)
* Added new …
> [FEAT] Add "auto" threshold configuration via Statistical analysis in SemanticChunker + minor fixes

- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
This pull request includes several changes to the `SDPMChunker`, `SemanticChunker`, and `SentenceChunker` classes to introduce a new parameter `delim` for specifying delimiters for sentence splitting. The changes also include updates to the `_split_sentences` method to utilize this new parameter.
* [`src/chonkie/chunker/sdpm.py`](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b8b54b082037R43): Added `delim` parameter to the `__init__` method and updated the docstring and initialization to include this parameter. [[1]](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b8b54b082037R43) [[2]](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b8b54b082037R58) [[3]](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b …
> Expose the seperation delim for simple multilingual chunking

- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/token.py
- src/chonkie/chunker/word.py
This pull request includes several changes to the `src/chonkie/chunker` module, focusing on improving the chunking process and refactoring the code for better readability and maintainability. The most important changes include modifications to the `_prepare_sentences` method, the introduction of the `_create_chunks` method, and updates to the chunking logic in both `token.py` and `word.py`.
* [`src/chonkie/chunker/sentence.py`](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cL256-R283): Removed the `_prepare_sentences` method and its associated logic, which was responsible for preparing sentences with estimated or accurate token counts. This method is now commented out.
* [`src/chonkie/chunker/token.py`](diffhunk://#diff-dc86e456384b2f6c8c9a959fa1aad45eecc4 …
> [Fix] #37: Incorrect indexing when repitition is present in the text

- README.md
- src/chonkie/chunker/late.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/types.py
- tests/chunker/test_late_chunker.py
This pull request introduces several enhancements and new features to the Chonkie library, particularly focusing on the addition of the experimental `LateChunker` and related functionalities. The most important changes include updates to the `README.md`, the `sentence_transformer.py` and `types.py` files, and the addition of new test cases for the `LateChunker`.
* **Documentation Update:**
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R91): Added a description for the new `LateChunker (experimental)` which embeds text and splits it to improve chunk embeddings.
* **Embedding Enhancements:**
* [`src/chonkie/embeddings/sentence_transformer.py`](diffhunk://#diff-a772f5d723fcdf86b61627ed9675d4441d0b7d3629ce7dbe9a355dab983f959bL44-R45): Added …
> Add initial support for Late Chunking

- README.md
- src/chonkie/chunker/late.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/types.py
- tests/chunker/test_late_chunker.py
This pull request introduces a new experimental chunker, `LateChunker`, and makes several enhancements to the embedding functionality. The most important changes include adding the `LateChunker` to the documentation, updating the `SentenceTransformer` embedding class to support token embeddings, and adding new data classes for `LateSentence` and `LateChunk`. Additionally, comprehensive test cases for the `LateChunker` have been added.
* **Documentation Update:**
- Added `LateChunker (experimental)` to the list of chunkers in `README.md`.
* **Embedding Enhancements:**
- Updated `SentenceTransformer` embedding class to import `numpy` and added methods to embed text as tokens and in batches. [[1]](diffhunk://#diff-a772f5d723fcdf86b61627ed9675d4441d0b7d3629ce7dbe9a355dab983f959bL44-R45) …
> [FEAT] Add LateChunker 

- .github/workflows/python-test-push.yml
- pyproject.toml
This pull request includes updates to the CI workflow and dependency versions to ensure compatibility and improve performance.
CI workflow update:
* [`.github/workflows/python-test-push.yml`](diffhunk://#diff-d6a8b1b38b2e521ccb0c938537c1a7d3f3ac92ce99c0ad84b849a2631f1f5662L13-R15): Updated the `astral-sh/setup-uv` action from version 3 to version 4 and added the `version: latest` parameter to ensure the latest version of `uv` is installed.
Dependency version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L40-R44): Updated the `numpy` dependency to specify an upper version limit of `<2.2` for all optional dependencies and increased the `sentence-transformers` dependency to version `3.0.0`.
> [FIX] Update outdated package versions + set max limit to numpy to v2.2 (buggy)

- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
This pull request includes small changes to the `__init__` methods in two files. The changes add support for additional keyword arguments (`**kwargs`) to enhance flexibility.
* [`src/chonkie/chunker/sdpm.py`](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b8b54b082037R61): Added `**kwargs` to the `__init__` method to allow additional keyword arguments.
* [`src/chonkie/chunker/semantic.py`](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7R59): Added `**kwargs` to the `__init__` method to allow additional keyword arguments.
> [fix] Docstrings in SemanticChunker should include **kwargs

- README.md
This pull request includes a small update to the `README.md` file. The change adds a Discord badge to the documentation section.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R12): Added a Discord badge with a link to the project's Discord server.
> [Minor] Add Discord badge to README for community engagement

- .github/workflows/python-test-push.yml
- README.md
- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chunker/__init__.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/embeddings/registry.py
- src/chonkie/refinery/base.py
- src/chonkie/refinery/overlap.py
- tests/refinery/test_overlap_refinery.py
This pull request introduces a new `RecursiveChunker` class and makes several updates to the `chonkie` library to support this new functionality. The most important changes include adding the `RecursiveChunker` class, updating the `README.md` to document the new chunker, and modifying various files to integrate the new chunker into the library.
* Added `RecursiveChunker` class to `src/chonkie/chunker/recursive.py`, which provides hierarchical text chunking using customizable rules.
* Updated `README.md` to include the `RecursiveChunker` in the list of available chunkers and changed the citation format to `bibtex`. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R90) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f …
> [FEAT] Add support for RecursiveChunking + minor fixes

- src/chonkie/chunker/token.py
- tests/chunker/test_token_chunker.py
…e (#84) (#109)
* [fix] #84: Add proper indices for Batch Token Chunking
* [fix] Indices incorrect due to Overlap
* Add a test case for batch token indices verification
> [fix] Correct the start and end indices for TokenChunker in Batch mode (#84)

- src/chonkie/chunker/token.py
- src/chonkie/refinery/base.py
- src/chonkie/refinery/overlap.py
- tests/chunker/test_token_chunker.py
- tests/refinery/test_overlap_refinery.py
This pull request includes several changes to the `semantic.py` file in the `src/chonkie/chunker` directory, as well as updates to the test files in the `tests/chunker` and `tests/embeddings` directories. The main focus of these changes is to improve the semantic chunking logic and update the test cases accordingly.
Improvements to semantic chunking logic:
* [`src/chonkie/chunker/semantic.py`](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L92-R92): Modified the `__init__` method to set `similarity_window` based on the mode.
* [`src/chonkie/chunker/semantic.py`](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7R250-R281): Replaced the `_compute_pairwise_similarities` method with `_compute_window_similarities` to handle …
> [fix] Add fix for #106: Reconstruction tests for SemanticChunker failing, missing last sentence

- LICENSE
- pyproject.toml
- src/chonkie/__init__.py
This pull request includes updates to the project metadata and licensing information. The most important changes include updating the project version and changing the copyright information.
Project metadata updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the project version from `0.3.0` to `0.4.0`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L37-R37): Updated the `__version__` attribute from `0.3.0` to `0.4.0`.
Licensing information update:
* [`LICENSE`](diffhunk://#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L3-R3): Updated the copyright holder from "Bhavnick Minhas" to "Chonkie AI".
> [chore] Bump version to "v0.4.0" + minor change

- .github/workflows/python-test-push.yml
- CONTRIBUTING.md
- src/chonkie/chunker/base.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/token.py
- src/chonkie/embeddings/base.py
- tests/chunker/test_recursive_chunker.py
- tests/chunker/test_word_chunker.py
- tests/embeddings/test_custom_embeddings.py
- tests/refinery/test_overlap_refinery.py
This pull request includes several updates and improvements to the `chonkie` project, focusing on enhancing tokenizer handling, updating documentation, and adding new test cases. Below are the most important changes:
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0R46-R51): Improved the `_get_tokenizer_backend`, `_get_tokenizer_counter`, `_encode`, `_encode_batch`, `_decode`, and `_decode_batch` methods to support callable tokenizer backends. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0R46-R51) [[2]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0R110-R111) [[3]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0R135- …
> [Fix] Add fix for #92: Support `class.method` as a Tokenizer for `CustomEmbedding` +. minor changes

- src/chonkie/chunker/token.py
I decoded each time the trailing `overlap_tokens` and then subtracted their space from the `end_index` so that I will get the `start_index` for the next chunk. Hence, we need not find the `chunk_text` in the `decoded_text`. Both the find() and `decoded_text` are not needed anymore. 
We have to subtract `chunk_size - current_token_count` because the last chunk may have lesser tokens than the `chunk_size`.
I timed the fixed old and the new method, here are the results:
`new valid approach`:
- 189 μs ± 5.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
- 195 μs ± 6.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
- 198 μs ± 2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
- 188 μs ± 2.98 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
- …
> [FIX] #116: Incorrect`start_index` when `chunk_overlap` is not 0

- src/chonkie/chunker/token.py
This pull request introduces changes to the `src/chonkie/chunker/token.py` file to improve the chunking process by refactoring how token groups are generated. The main change involves moving the `_token_group_generator` method to a more appropriate location within the file and integrating its usage more consistently across the codebase.
Key changes include:
* Refactoring `_token_group_generator`:
* Moved `_token_group_generator` method to a more appropriate location within the file.
* Updated the `chunk` method to use `_token_group_generator` for calculating token groups.
* Modified the `_process_text_batch` method to use `_token_group_generator` for generating token groups.
> [fix] High `chunk_overlap` causes last chunk to be entirely redundant

- src/chonkie/chunker/recursive.py
This pull request includes a change to the `_split_text` method in the `src/chonkie/chunker/recursive.py` file to enhance the handling of short text splits by merging them more effectively.
Enhancements to text splitting:
* [`src/chonkie/chunker/recursive.py`](diffhunk://#diff-8bbe8a372641303a22785a4d84abd72a02d9cad7afe7d7055d0f9581cae268b7L56-R62): Modified the `_split_text` method to use an index-based loop and handle cases where `merged_splits` is empty by merging the current split with the next one.
> [FIX] Handle edge case for RecursiveChunker (#131)

- src/chonkie/chunker/base.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/token.py
- src/chonkie/embeddings/auto.py
- src/chonkie/embeddings/base.py
This pull request includes several changes to the `chonkie` package, focusing on updating progress bar descriptions, improving error messages, and adding docstrings for better code clarity. The most important changes include modifications to progress bar descriptions in multiple files, updates to error messages in `semantic.py`, and the addition of docstrings in `auto.py` and `base.py`.
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L249-R253): Updated progress bar descriptions in `_process_batch_sequential` and `_process_batch_multiprocessing` methods to use "doc" instead of "texts" and changed the bar format and ASCII style. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L249-R253) …
> [FIX] Minor fixes + Stylistic enhancements for TQDM and Multiprocessing

- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/token.py
- src/chonkie/chunker/word.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
- tests/chunker/test_sentence_chunker.py
- tests/chunker/test_token_chunker.py
- tests/chunker/test_word_chunker.py
This pull request introduces a new feature to the chunking modules, allowing them to return either chunks or raw texts based on a new parameter `return_type`. Additionally, it includes validation checks for the new parameter and updates to the chunk creation logic to accommodate this change.
* [`src/chonkie/chunker/recursive.py`](diffhunk://#diff-8bbe8a372641303a22785a4d84abd72a02d9cad7afe7d7055d0f9581cae268b7L5-R5): Added `return_type` parameter to the `__init__` method and included validation checks. Updated `_recursive_chunk` method to handle both "chunks" and "texts" return types. [[1]](diffhunk://#diff-8bbe8a372641303a22785a4d84abd72a02d9cad7afe7d7055d0f9581cae268b7L5-R5) [[2]](diffhunk://#diff-8bbe8a372641303a22785a4d84abd72a02d9cad7afe7d7055d0f9581cae268b7L24-R25) …
> [FEAT] Support `return_type` as `texts` for direct text handling

- benchmarks/README.md
This pull request includes significant updates to the `benchmarks/README.md` file, focusing on enhancing the speed benchmarks and reorganizing the size comparison sections. The most important changes include updating benchmark results for various datasets and reformatting the document for clarity.
Updates to speed benchmarks:
* Added new benchmarks for 100K and 500K Wikipedia articles, including token chunking, sentence chunking, recursive chunking, and semantic chunking.
* Updated the Paul Graham Essays dataset benchmarks to include more detailed timing results.
Reorganization of size comparison sections:
* Moved the size comparison section to the end of the document and updated the package sizes for `Chonkie`, `LangChain`, and `LlamaIndex`.
* Reformatted the document to improve …
> [DOCS] Update Benchmarks - Include Wikipedia-100k and Wikipedia-500k run timings

- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sentence.py
- src/chonkie/types.py
This pull request includes several changes to improve the documentation, update type hints, and enhance chunking functionality. The most important changes include updating the benchmarks in the `README.md`, adding type hints, and modifying chunking logic to handle delimiters more flexibly.
Documentation updates:
* [`benchmarks/README.md`](diffhunk://#diff-576c27794bae284efc278336a16d0649aaf599973a64d4b65dc67bc99bb7f000L7-R152): Updated the benchmarks to include more detailed speed and size comparisons across different datasets and chunking methods.
Type hints and imports:
* [`src/chonkie/chunker/recursive.py`](diffhunk://#diff-8bbe8a372641303a22785a4d84abd72a02d9cad7afe7d7055d0f9581cae268b7L5-R5): Updated type hints for consistency and clarity. …
> [Feat] Add `include_delim='next'` as an optional argument in SentenceChunker and RecursiveChunker

- src/chonkie/chunker/sentence.py
- tests/chunker/test_sentence_chunker.py
This pull request introduces several changes to the `SentenceChunker` class in the `src/chonkie/chunker/sentence.py` file to improve its functionality and robustness. Additionally, it includes a new test to ensure the new functionality works as expected.
Improvements to `SentenceChunker`:
* [`src/chonkie/chunker/sentence.py`](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cL10-R10): Added import for `warnings` module to handle warnings when the minimum sentences per chunk cannot be met.
* [`src/chonkie/chunker/sentence.py`](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cL118-R118): Modified `_split_sentences` method to remove unnecessary `strip()` call when checking sentence length.
* …
> [Fix] #151: Provide warning to user when `min_sentences_per_chunk` is not satisfied

- src/chonkie/chunker/late.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- tests/chunker/test_recursive_chunker.py
- tests/chunker/test_sentence_chunker.py
This pull request includes several changes to the chunking functionality, focusing on the handling of delimiters, sentence splitting, and ensuring minimum characters per chunk or sentence. The most important changes include adding the `include_delim` parameter, modifying sentence splitting logic, and updating test cases to cover new functionality.
Enhancements to chunking functionality:
* [`src/chonkie/chunker/late.py`](diffhunk://#diff-b8d4de839dd57d649b54fd5627f9cb77749311ee5e9965e7038f2bbddaed7277R35): Added the `include_delim` parameter to the `LateChunker` class and updated the `_split_sentences` method to handle this parameter. [[1]](diffhunk://#diff-b8d4de839dd57d649b54fd5627f9cb77749311ee5e9965e7038f2bbddaed7277R35) [[2]](diffhunk://#diff-b8d4de839dd57d649b54fd5627f9cb77749311ee5e9 …
> [Fix] Correct the `_split_text`/`_split_sentence` logic to give proper splits

- .gitignore
- cookbook/tutorials/recursive_chunking_pdf.ipynb
- src/chonkie/__init__.py
- src/chonkie/embeddings/__init__.py
- src/chonkie/embeddings/cohere.py
- src/chonkie/embeddings/registry.py
- src/chonkie/refinery/overlap.py
- src/chonkie/tokenizer.py
- src/chonkie/types.py
- tests/chunker/test_semantic_chunker.py
- tests/chunker/test_sentence_chunker.py
- tests/embeddings/test_auto_embeddings.py
- tests/embeddings/test_cohere_embeddings.py
- tests/refinery/test_overlap_refinery.py
This pull request includes various changes to the `chonkie` package, focusing on embedding imports, docstring updates, and significant enhancements to the `OverlapRefinery` class. The most important changes include reordering imports, updating docstrings for consistency, and adding new methods to support recursive context handling in the `OverlapRefinery` class.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408R16-L19): Reordered imports to maintain alphabetical order.
* [`src/chonkie/embeddings/__init__.py`](diffhunk://#diff-69b9908d38d6daa74572c7f51e92812b512ae8a4ed3bdce990a436eee53c6137R3-L6): Reordered imports to maintain alphabetical order.
* [`src/chonkie/embeddings/registry.py`](diffhunk://#diff-24ac16f8df6174d5a648298f8b …
> [Feat] Add `mode="recursive"` in `OverlapRefinery` for all methods

- pyproject.toml
- src/chonkie/__init__.py
This pull request includes a version update for the `chonkie` project. The version has been incremented from `0.5.0` to `0.5.1` in both the `pyproject.toml` file and the `src/chonkie/__init__.py` file.
Version update:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the `version` field from `0.5.0` to `0.5.1`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L46-R46): Updated the `__version__` attribute from `0.5.0` to `0.5.1`.
> [Chore] Bump version to v0.5.1

- src/chonkie/chef/patterns.py
- src/chonkie/chef/text.py
- tests/chef/test_text_chef.py
Stuff:
1. Abbreviations with a word boundary at start and a non-word character at the end will only be replaced. 
Example: dot in "in." in someone@domain.org will not be replaced. But, dot in "in." in "My height is 6 in. and my weight is 65 kg." gets replaced with the dot leader.
2. Abbreviations that end the text (not sentence) will not get replaced. As it is not necessary. 
> Note: Have to find a proper way so that abbreviations at the end of the sentences will also remain not replaced. 
3. Abbreviations having larger length will get processed before the ones with shorted lengths. This helps to handle the cases where the prefixes of a abbreviation exist in another abbreviation. 
4. An email regex used to replace the dots in emails with dot leaders.
5. An URL regex used to replace the …
> [FEAT] Addition of decimal point, emails and urls handling. Better abbreviation handling.

- src/chonkie/embeddings/cohere.py
This pull request includes several changes to the `src/chonkie/embeddings/cohere.py` file, focusing on improving type hinting and ensuring that certain imports are only included during type checking. The main changes are as follows:
Type Hinting Improvements:
* Changed the return type of the `embed` method to use a string type hint for `np.ndarray`.
* Updated the `embed_batch` method to use a string type hint for `List[np.ndarray]`.
* Modified the `similarity` method to use string type hints for `np.ndarray` and `np.float32`.
* Added return type hints for `get_tokenizer_or_token_counter` method.
Conditional Imports:
* Added `TYPE_CHECKING` import and conditionally imported `numpy` and `tokenizers` to avoid unnecessary imports during runtime. …
> Fix: shift to lazy imports inside `CohereEmbeddings`
