chonkie-ai/chonkie

- DOCS.md
- README.md
- pyproject.toml
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
- tests/chunker/test_sentence_chunker.py
This pull request includes various updates to the `Chonkie` documentation and codebase, focusing on improving documentation clarity, simplifying chunker initialization, and removing dependencies on `spaCy`.
* Improved wording and capitalization in `DOCS.md` to enhance readability and professionalism. [[1]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L3-R3) [[2]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L46-R67)
* Added a new FAQ section in `DOCS.md` to address common questions about Chonkie's thread-safety and usage. [[1]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L34-R35) [[2]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054R357-R364)
* …
> Remove Spacy dependency from Chonkie

- DOCS.md
- pyproject.toml
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/embeddings/__init__.py
- src/chonkie/embeddings/base.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
This pull request includes significant updates to the `chonkie` package, primarily focusing on removing the dependency on tokenizers and enhancing the chunking and embeddings functionalities. The most important changes include the removal of the tokenizer from the chunkers, the addition of a new base embeddings class, and updates to the documentation and tests to reflect these changes.
* [`src/chonkie/chunker/sdpm.py`](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b8b54b082037R7-L9): Removed the `tokenizer` parameter from the `SDPMChunker` class and its initialization. Updated the class docstring and method arguments accordingly. [[1]](diffhunk://#diff-359202635006b02c57f41dbefe88292468e723829ac8579c6086b8b54b082037R7-L9) …
> fix: tokenizer mismatch for `SemanticChunker` + Add BaseEmbeddings

- DOCS.md
- src/chonkie/chunker/base.py
This pull request includes updates to the `TokenChunker` class and its documentation to improve usability and performance. Key changes include the addition of multiprocessing for batch chunking, enhanced documentation, and the ability to handle both single and batch inputs using the `__call__` method.
* [`DOCS.md`](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054R193-R255): Added detailed descriptions for key parameters and methods of the `TokenChunker` class, along with example usage.
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L4-R7): Added multiprocessing support for the `chunk_batch` method to improve performance by parallelizing the chunking process. …
> Add initial batching support via `chunk_batch` fn + update DOCS

- src/chonkie/chunker/base.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
This pull request includes changes to various dataclasses to improve performance by using `__slots__` and adding detailed docstrings for better documentation. The most important changes include modifications to the `Chunk`, `SemanticSentence`, `SemanticChunk`, `Sentence`, and `SentenceChunk` classes.
Changes to dataclasses for performance and documentation:
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L9-R26): Modified the `Chunk` class to use `__slots__` for performance and added detailed docstrings.
* [`src/chonkie/chunker/semantic.py`](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L13-R57): Modified the `SemanticSentence` class to use `__slots__` for performance, added detailed …
> Use `__slots__` instead of `slots=True` for python3.9 support

- src/chonkie/chunker/base.py
- src/chonkie/chunker/semantic.py
- src/chonkie/embeddings/auto.py
- src/chonkie/embeddings/base.py
- src/chonkie/embeddings/sentence_transformer.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
This pull request includes several changes to improve the flexibility and functionality of the chunking and embedding models in the `chonkie` package. The most important changes include updating the `BaseChunker` class to support token counters, modifying the `SemanticChunker` to use the new embedding model interface, and updating the tests to reflect these changes.
Enhancements to `BaseChunker`:
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L4-R4): Updated the `BaseChunker` class to accept a callable tokenizer or token counter, added methods to count tokens and batch count tokens, and adjusted the initialization logic to handle different types of tokenizers. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c …
> Refactor BaseChunker, SemanticChunker and SDPMChunker to support BaseEmbeddings 

- DOCS.md
- pyproject.toml
This pull request includes significant updates to the `DOCS.md` file and a minor change to the `pyproject.toml` file. The changes primarily focus on improving the documentation for installation options and embedding features.
Documentation updates:
* [`DOCS.md`](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L11-R14): Added new sections for "Dependency Tables" and "Embeddings," including detailed tables for chunker and embedding availability, required dependencies, and installation commands. [[1]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L11-R14) [[2]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054R32-R37) [[3]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7 …
> [DOCS] Add info about initial embeddings support and how to add custom embeddings

- src/chonkie/chunker/base.py
- tests/chunker/test_token_chunker.py
This pull request includes changes to the `src/chonkie/chunker/base.py` file to update the tokenization process, as well as new tests in the `tests/chunker/test_token_chunker.py` file to ensure the functionality of the updates. The most important changes include modifications to the tokenizer encoding methods to exclude special tokens and the addition of new test cases for different tokenizers.
Changes to tokenization methods:
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L112-R114): Updated the `_get_tokenizer_counter`, `_encode`, and `_encode_batch` methods to exclude special tokens by setting `add_special_tokens=False` in the `encode` and `batch_encode_plus` methods for the "transformers" and "tokenizers" backends. …
> [Fix] Token counts from Tokenizers and Transformers adding special tokens

- DOCS.md
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/word.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
- tests/chunker/test_sentence_chunker.py
- tests/chunker/test_token_chunker.py
- tests/chunker/test_word_chunker.py
This pull request primarily focuses on renaming the `max_chunk_size` parameter to `chunk_size` across various files and methods, and optimizing the sentence splitting method for better performance and accuracy. Below are the most important changes:
* [`DOCS.md`](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L417-R417): Renamed `max_chunk_size` to `chunk_size` in the documentation for `SemanticChunker` and `SDPMChunker` classes. [[1]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L417-R417) [[2]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L447-R447) [[3]](diffhunk://#diff-3f4fe07ebe4ba7ea65472755ddc67a72905bc98e55b5b84a2055c7e36b6f1054L467-R467) …
> [Fix] Refactor WordChunker, SentenceChunker pre-chunk splitting for reconstruction tests + minor changes

- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
This pull request includes changes to the sentence splitting functionality in the `src/chonkie/chunker/semantic.py` and `src/chonkie/chunker/sentence.py` files. The changes introduce a new parameter to handle minimum sentence length and modify the splitting logic accordingly.
Enhancements to sentence splitting:
* [`src/chonkie/chunker/semantic.py`](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L121-R122): Added a `min_length` parameter to the `_split_sentences` method to ensure sentences below a certain length are combined with the previous sentence. Updated the splitting logic to accommodate this new parameter. [[1]](diffhunk://#diff-146b453f965159091625de58459bbbec8804c130d022226f0186b4439e1ba1d7L121-R122) …
> [Fix] Add fix for #55

- .github/workflows/tests.yml
- README.md
- pyproject.toml
- tests/chunker/test_semantic_chunker.py
- tests/embeddings/test_openai_embeddings.py
I have added a small documentation on how to setup local env for testing.
**Changes in pyproject.toml**
`pytest` was not picking up local changes. It was giving `ModuleNotFoundError` error for `chonkie`. Adding `pythonpath` fixed that.
**Automated Testing**
I have also added a github action to run the tests automatically on each `git push`. I have used `uv` because of superfast dependency installation.
I followed this guide for the GitHub Actions setup: https://docs.astral.sh/uv/guides/integration/github/
> Added automated testing using Github Actions

- src/chonkie/chunker/base.py
This pull request introduces several enhancements and optimizations to the `SentenceChunker` class in the `src/chonkie/chunker/sentence.py` file. The changes include the addition of new methods for estimating token counts, improvements to the chunking logic, and the introduction of a feedback mechanism for refining token count estimates.
* Added new methods `_estimate_token_counts` and `_get_feedback` to estimate token counts using character length and validate estimates against actual token counts. [[1]](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cR257-R271) [[2]](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cL263-R342)
* Improved the `_prepare_sentences` method to support both estimated and accurate token counts, …
> Add TEVL to speed-up sentence chunking

- src/chonkie/chunker/base.py
- tests/chunker/test_word_chunker.py
Fix for #73 
Issue was that lambdas are not serializable
@bhavnicksm lmk if this works
> [Fix] WordChunker chunk_batch fail

- pyproject.toml
- src/chonkie/__init__.py
- Bump project version to 0.3.0 to reflect new features and improvements.
- Add support for Python 3.13 in project classifiers.
> Update version to 0.3.0 in pyproject.toml and __init__.py

- .github/workflows/python-test-push.yml
This pull request includes updates to the `.github/workflows/python-test-push.yml` file to improve the setup and execution of Python tests and the handling of test results.
Improvements to test setup and execution:
* Modified the installation process to create and activate a virtual environment, then install necessary packages including `pytest`, `pytest-cov`, and `coverage`.
* Updated the test execution command to use the activated virtual environment and added additional options to the `pytest` command for better coverage reporting.
Enhancements to test result handling:
* Added a new step to upload test results to Codecov, ensuring that the results are uploaded even if the workflow is not canceled.
> [fix] CI: reports were not being uploaded to Codecov

- CONTRIBUTING.md
> Update CONTRIBUTING.md with first issue hyperlink

- src/chonkie/chunker/base.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/token.py
- src/chonkie/embeddings/base.py
- tests/chunker/test_recursive_chunker.py
- tests/chunker/test_word_chunker.py
- tests/embeddings/test_custom_embeddings.py
- tests/refinery/test_overlap_refinery.py
This pull request includes several changes to the `chonkie` library, focusing on improving tokenizer handling, simplifying the codebase, and adding new tests for the `CustomEmbeddings` class. The most important changes include modifications to the tokenizer handling logic, removal of unnecessary imports, and the addition of test cases.
Improvements to tokenizer handling:
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L33-L38): Refactored the tokenizer handling logic to support callable tokenizers, including updates to `_get_tokenizer_backend`, `_get_tokenizer_counter`, `_encode`, `_encode_batch`, `_decode`, and `_decode_batch` methods. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L …
> [FIX]  Support class methods as `token_counter` objects for `CustomEmbeddings` (#92)

- README.md
Update readme intro match chonkie.ai docs.
> Update readme intro to match docs.

- README.md
- src/chonkie/chunker/base.py
- src/chonkie/chunker/late.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/token.py
- src/chonkie/chunker/word.py
This pull request includes several changes to enhance the functionality and usability of the `chonkie` library. The most important changes involve improvements to the chunking process, the addition of progress bars, and updates to the documentation.
* [`src/chonkie/chunker/base.py`](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L12-R12): Introduced multiprocessing and sequential processing methods for batch chunking, with the ability to show progress bars using `tqdm`. Added a new flag `_use_multiprocessing` to control multiprocessing usage. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L12-R12) [[2]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0R38-R40) …
> [FEAT] Add TQDM progress bars for `chunk_batch` + Update README.md

- README.md
Existing invite expired, replacing with infinite life one.
> Replace dead discord link with infinite lifetime

- pyproject.toml
- src/chonkie/__init__.py
This pull request includes a couple of minor updates to the `chonkie` project, specifically updating the version number and author information.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the project version from `0.4.0` to `0.4.1`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L37-R39): Updated the version number to `0.4.1` and changed the author from "Bhavnick Minhas" to "Chonkie AI".
> [chore] Bump up the package version to v0.4.1

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- benchmarks/README.md
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/token.py
- src/chonkie/chunker/word.py
- src/chonkie/embeddings/base.py
- src/chonkie/embeddings/model2vec.py
- src/chonkie/embeddings/openai.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/types.py
This pull request includes several changes to the Chonkie library, focusing on improving the documentation, enhancing chunking methods, and optimizing imports. The most important changes include updates to the benchmarks in the `README.md`, enhancements to the chunking methods, and conditional imports for optional dependencies.
Documentation Updates:
* [`benchmarks/README.md`](diffhunk://#diff-576c27794bae284efc278336a16d0649aaf599973a64d4b65dc67bc99bb7f000L7-R152): Updated the speed benchmarks section with detailed results for different chunking methods and datasets, and moved the size comparison section.
Enhancements to Chunking Methods:
* [`src/chonkie/chunker/sentence.py`](diffhunk://#diff-f8621e6d7d2b3c3d8fecdaf6ec442aefbd9acecf06764aed2d6953b6e995ee7cL15-R23): Added support for …
> Update Benchmarks + Remove numpy base dependency + Add `include_delim` in Chunkers

- README.md
- pyproject.toml
- src/chonkie/chunker/base.py
- src/chonkie/refinery/overlap.py
- tests/chunker/test_sentence_chunker.py
This pull request includes significant updates to the tokenizer handling in the `chonkie` project, as well as updates to the documentation to reflect these changes. The main changes involve replacing the `autotiktokenizer` library with the `tokenizers` library, adding support for multiple tokenizer backends, and updating the README to reflect the new package size.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L34-R34): Replaced `autotiktokenizer` with `tokenizers` and updated dependencies to include `tiktoken` for the `openai` optional dependency. [[1]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L34-R34) [[2]](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L45-R49 …
> [Fix] Default to Tokenizers while AutoTikTokenizer issues are resolved

- pyproject.toml
- src/chonkie/__init__.py
This pull request includes version updates and minor metadata changes for the `chonkie` package.
Version updates:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L7-R7): Updated the version from `0.4.1` to `0.5.0`.
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L39-R42): Updated the version from `0.4.1` to `0.5.0`.
Metadata changes:
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L39-R42): Changed the author from "Chonkie AI" to "🦛 Chonkie AI Team".
* [`src/chonkie/__init__.py`](diffhunk://#diff-44a557df57b150a7b71a0b691e66e501f00f8983cc9c66dee9309aaf738bd408L39-R42): Added a comment "This hippo grows with …
> Bump up version to `v0.5.0`

- src/chonkie/types.py
This pull request introduces methods to convert various dataclass objects to and from dictionaries for consistency across the codebase. The changes span multiple classes within the `src/chonkie/types.py` file.
Key changes include:
* `Context` class: Added `to_dict` and `from_dict` methods to convert the `Context` object to and from a dictionary.
* `Chunk` class: Added `to_dict` and `from_dict` methods to convert the `Chunk` object to and from a dictionary, including nested `Context` objects.
* `Sentence` class: Added `to_dict` and `from_dict` methods to convert the `Sentence` object to and from a dictionary.
* `SentenceChunk` class: Added `to_dict` and `from_dict` methods to convert the `SentenceChunk` object to and from a dictionary, including nested `Sentence` objects.
* …
> Add `to_dict` and `from_dict` to all Chonkie data-classes

- src/chonkie/types.py
- tests/test_types.py
This pull request includes several modifications to the `src/chonkie/types.py` file and adds new tests in the `tests/test_types.py` file. The most important changes involve refactoring methods to remove unnecessary calls to `super().from_dict(data)` and adding comprehensive tests for various types.
Refactoring in `src/chonkie/types.py`:
* Removed unnecessary calls to `super().from_dict(data)` in multiple `from_dict` methods to simplify the code. [[1]](diffhunk://#diff-198c3a64562b333dd5b819d19fe9a8c1d76e400f6da24bd2070fa6d5f995e4a7L209-R214) [[2]](diffhunk://#diff-198c3a64562b333dd5b819d19fe9a8c1d76e400f6da24bd2070fa6d5f995e4a7L247-R252) [[3]](diffhunk://#diff-198c3a64562b333dd5b819d19fe9a8c1d76e400f6da24bd2070fa6d5f995e4a7L281-R284) …
> Add tests for types.py + Make the tests pass :)

- cookbook/tutorials/Chonkie_RecursiveChunker_for_PDF_and_Markdown.ipynb
This PR makes a minor addition to the `Chonkie_RecursiveChunker_for_PDF_and_Markdown.ipynb`, during initialization adds the `include_delim="next"` to keep the `#` in the next chunk.
> Add `include_delim="next"` for headings in tutorial

- src/chonkie/chunker/late.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/token.py
- src/chonkie/embeddings/base.py
- src/chonkie/embeddings/cohere.py
- src/chonkie/embeddings/model2vec.py
- src/chonkie/embeddings/openai.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/refinery/overlap.py
This pull request introduces lazy loading for dependencies across various modules to improve performance by avoiding unnecessary imports. The most significant changes include the addition of `_import_dependencies` methods and modifications to the initialization process in multiple classes.
* [`src/chonkie/chunker/late.py`](diffhunk://#diff-b8d4de839dd57d649b54fd5627f9cb77749311ee5e9965e7038f2bbddaed7277R71-R73): Added `_import_dependencies` method and modified the `__init__` method to call this method for lazy loading dependencies like `numpy`. [[1]](diffhunk://#diff-b8d4de839dd57d649b54fd5627f9cb77749311ee5e9965e7038f2bbddaed7277R71-R73) [[2]](diffhunk://#diff-b8d4de839dd57d649b54fd5627f9cb77749311ee5e9965e7038f2bbddaed7277L109-L113) …
> [Feat] Default to Lazy Imports in classes to improve import time

- .gitignore
- pyproject.toml
- src/chonkie/chef/base.py
- src/chonkie/chunker/base.py
- src/chonkie/chunker/late.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/token.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/tokenizer.py
- src/chonkie/types.py
- tests/chef/test_text_chef.py
This pull request includes several changes to improve type consistency and handle edge cases in the `chonkie` library. The most important changes involve updating type annotations to use `Sequence` instead of `List`, adding handling for empty or single string inputs, and ensuring proper return types.
Improvements to type consistency:
* Updated type annotations from `List` to `Sequence` in various methods across multiple files, including `src/chonkie/chunker/base.py`, `src/chonkie/chunker/late.py`, `src/chonkie/chunker/recursive.py`, and `src/chonkie/chunker/token.py`. This change ensures more flexible and consistent handling of different sequence types. [[1]](diffhunk://#diff-10846354259652bb75e491a4bbce39e3909b204c82e70145936f910655ad97a0L37-R37) …
> [Fix] Solve a few static type checking errors from mypy

- cookbook/README.md
- src/chonkie/embeddings/sentence_transformer.py
This pull request includes several updates to the documentation and codebase of the Chonkie project. The most important changes include adding new integrations and resources to the `cookbook/README.md` file and adding type hints to methods in the `sentence_transformer.py` file.
* [`cookbook/README.md`](diffhunk://#diff-3029b5c637461a29ab9b04b47fdf828e2b5a96414348159214cd18c8e09942a2R27-R41): Added new integrations for PraisonAI and SurfSense, and new community resources including projects and blogs.
* [`src/chonkie/embeddings/sentence_transformer.py`](diffhunk://#diff-a772f5d723fcdf86b61627ed9675d4441d0b7d3629ce7dbe9a355dab983f959bL62-R62): Added `# type: ignore` comments to methods `embed`, `embed_as_tokens`, `get_tokenizer_or_token_counter`, and `max_seq_length` to suppress type …
> [Community] Update the ChonkBook 🦛

- .github/workflows/python-test-push.yml
- pyproject.toml
- src/chonkie/cloud/__init__.py
- src/chonkie/cloud/chunker/__init__.py
- src/chonkie/cloud/chunker/base.py
- src/chonkie/cloud/chunker/late.py
- src/chonkie/cloud/chunker/recursive.py
- src/chonkie/cloud/chunker/sdpm.py
- src/chonkie/cloud/chunker/semantic.py
- src/chonkie/cloud/chunker/sentence.py
- src/chonkie/cloud/chunker/token.py
- src/chonkie/cloud/chunker/word.py
- tests/chunker/test_late_chunker.py
- tests/chunker/test_token_chunker.py
- tests/cloud/test_cloud_late_chunker.py
- tests/cloud/test_cloud_recursive_chunker.py
- tests/cloud/test_cloud_sdpm_chunker.py
- tests/cloud/test_cloud_semantic_chunker.py
- tests/cloud/test_cloud_sentence_chunker.py
- tests/cloud/test_cloud_token_chunker.py
- tests/cloud/test_cloud_word_chunker.py
- tests/embeddings/test_auto_embeddings.py
- tests/embeddings/test_cohere_embeddings.py
- tests/embeddings/test_custom_embeddings.py
- tests/embeddings/test_model2vec_embeddings.py
- tests/embeddings/test_openai_embeddings.py
- tests/embeddings/test_sentence_transformer_embeddings.py
- tests/test_tokenizer.py
This pull request introduces the new `chonkie.cloud` module and its associated chunkers, along with updates to the project configuration. The most important changes include the addition of the `chonkie.cloud` package, new chunker classes for various chunking algorithms, and updates to the `pyproject.toml` file.
New `chonkie.cloud` package and chunkers:
* [`src/chonkie/cloud/__init__.py`](diffhunk://#diff-d755310e35499ddbbf52812fca4020d8ee4f16ca454281516ec8769890295369R1-R22): Added the `chonkie.cloud` module with imports and `__all__` for the new chunker classes.
* [`src/chonkie/cloud/chunker/__init__.py`](diffhunk://#diff-3ba5ec3dca2b44fc8b4a2a2f4410f1782ee388d44112cf2253df4f3d8385d357R1-R21): Introduced the `chonkie.cloud.chunker` module with imports and `__all__` for the new chunker …
> Add initial support for Chonkie Cloud Client 

- .gitignore
- README.md
- cookbook/README.md
- cookbook/tutorials/Chonkie_RecursiveChunker_for_PDF_and_Markdown.ipynb
- pyproject.toml
- src/chonkie/__init__.py
- src/chonkie/chef/base.py
- src/chonkie/chunker/base.py
- src/chonkie/chunker/late.py
- src/chonkie/chunker/recursive.py
- src/chonkie/chunker/sdpm.py
- src/chonkie/chunker/semantic.py
- src/chonkie/chunker/sentence.py
- src/chonkie/chunker/token.py
- src/chonkie/chunker/word.py
- src/chonkie/embeddings/auto.py
- src/chonkie/embeddings/cohere.py
- src/chonkie/embeddings/openai.py
- src/chonkie/embeddings/sentence_transformer.py
- src/chonkie/refinery/overlap.py
- src/chonkie/tokenizer.py
- src/chonkie/types.py
- tests/chef/test_text_chef.py
- tests/chunker/test_sdpm_chunker.py
- tests/chunker/test_semantic_chunker.py
- tests/chunker/test_sentence_chunker.py
- tests/refinery/test_overlap_refinery.py
This pull request introduces significant enhancements to the Chonkie Cloud APIs, including the addition of new modules and classes for various chunking algorithms, as well as updates to the project configuration and test workflows.
* [`src/chonkie/cloud/__init__.py`](diffhunk://#diff-d755310e35499ddbbf52812fca4020d8ee4f16ca454281516ec8769890295369R1-R22): Added a new module for Chonkie Cloud APIs with imports for various chunkers.
* [`src/chonkie/cloud/chunker/__init__.py`](diffhunk://#diff-3ba5ec3dca2b44fc8b4a2a2f4410f1782ee388d44112cf2253df4f3d8385d357R1-R21): Introduced a new module for Chonkie Cloud Chunkers, including the `CloudChunker` base class and specific chunker implementations.
* [`src/chonkie/cloud/chunker/base.py`](diffhunk://#diff-af2caee21a3db2cba2fd45bcc0e9c6a77c6dcdf1c67b …
> Add initial support for 🦛 Chonkie Cloud ☁️ client 

- README.md
This pull request includes a small update to the `README.md` file. The change adds a new badge for code coverage using Codecov.
Changes in `README.md`:
* Added a Codecov badge to display code coverage statistics.
> Add code-cov badge to the README.md
